# Generated by Django 5.0.6 on 2024-07-08 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameModel(
            old_name='Klass',
            new_name='FoodType',
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tarkibi', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('foodtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.foodtype')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogapp.food'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
